config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    resources :likes
  end
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  get 'posts/index'
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :likes
  validates :title,
            presence: true
  validates :content,
            presence: true
  validates :user,
            presence: true
  def to_s
    title
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :destroy

  validates :nick, presence:true,uniqueness:true
  validates :departmant, presence:true

  def to_s
  	"#{nick}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
	  def current_user
	    User.where(id: session[:user_id]).first
	  end
  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.userName = current_user.nick
    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @post = Post.find(params[:post_id])
    @comment.destroy
    redirect_to @post, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:comm)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  def index
    @likes = Like.all
  end

  # GET /likes/1
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create(like_params)
    @like.userNameLiked = current_user.nick

    if @like.save
      redirect_to @post
    else
      render :new
    end
  end

  # PATCH/PUT /likes/1
  def update
    if @like.update(like_params)
      redirect_to @like, notice: 'Like was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /likes/1
  def destroy
    @post = Post.find(params[:post_id])
    @like.destroy
    redirect_to @post
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def like_params
    end

    def getAdmin
      if current_user.nick != "admin"
        redirect_to login_url, alert: "Not authorized! Please login as admin."
      end
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit( :title, :content)
    end

    def authorize
      if current_user.nil?
        redirect_to login_url, alert: "Not authorized! Please log in."
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_nick(params[:nick])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :getAdmin, only: [:destroy]
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to posts_url, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:nick, :departmant, :password, :password_confirmation)
    end

    def getAdmin
      if current_user && current_user.nick != "admin"
        redirect_to login_url, alert: "Not authorized! Please login as admin."
      end
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :userName %><br>
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :comm %><br>
    <%= f.text_area :comm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Username</th>
      <th>Comm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post %></td>
        <td><%= comment.userName %></td>
        <td><%= comment.comm %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p class="new">
<%= link_to 'New Comment', new_comment_path %>
</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<p class="new">
<%= link_to 'Back', comments_path %>	
</p>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p class="new">
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p class="new">
  <strong>Username:</strong>
  <%= @comment.userName %>
</p>

<p class="new">
  <strong>Comm:</strong>
  <%= @comment.comm %>
</p>

<p class="new">
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>	
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WallApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'myStyle' %>
</head>
  <body style="background-color: lightblue;" >
<!--
  <header>
    <div class="nav">
      <ul>
        <li><a class="active" href="#"><%= link_to 'Home', root_path %></a></li>
        <li><a href="#"><%= link_to 'Posts', posts_path %></a></li>
        <% if current_user %>
        <li><a href="#">
				<li><%= link_to "Log Out", logout_path %></li>
        	</a>
        </li>
        <% end %>
        <% if current_user.nil? %>
        <li><a href="#">
				 <li><%= link_to "Sign Up", signup_path %></li>
				 <li><%= link_to "Log In", login_path %></li>
		     </a>
        </li>
        <% end %>
      </ul>
    </div>
  </header>
-->
	<div class="nav">
		 <li><%= link_to 'Posts', posts_path %> </li>
		 <% if current_user %>
		 <li><%= link_to "Log Out", logout_path %></li>
		 <% else %>
		 <li><%= link_to "Sign Up", signup_path %></li>
		 <li><%= link_to "Log In", login_path %></li>
		 <% end %>
	</div>




  <img align="center" src="/gtu.png"  height="180" width="300">
	<% flash.each do |key, value| %>
		<%= content_tag(:div, class: "alert alert-#{key}") do %>
	<p><%= value %></p>
	 <% end %>
	<% end %>


<%= yield %>

</body>
</html>

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :userNameLiked %><br>
    <%= f.text_field :userNameLiked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Likes</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Usernameliked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.post %></td>
        <td><%= like.userNameLiked %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @like.post %>
</p>

<p>
  <strong>Usernameliked:</strong>
  <%= @like.userNameLiked %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

<% if current_user.nil? %>

<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Gönder" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WallApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'myMain' %>

</head>

<body style="background-color: lightblue;">
    <p>
    <div style="width: 50%;margin-left: 25%;margin-right: 25%;background-color: white;">
        <table border="2">
          <tr>
            <td>
				<h1>Editing Post</h1>
				<%= render 'form' %>
				<p>
				<%= link_to 'Göster', @post %> |
				<%= link_to 'Geri dön', posts_path %>
				</p>             

            </td>
          </tr>
        </table>
    </div>



</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WallApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'myMain' %>

</head>
  <body style="background-color: lightblue;" >
    
    <h1> <%= current_user.departmant %> Bölümü </h1>
    <!--
    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Title</th>
          <th>Content</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.reverse.each do |post| %>
          <tr>
            <td><%= post.user %></td>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td><%= link_to 'Show', post %></td>
            <td><% if current_user && post.user == current_user %><%= link_to 'Edit', edit_post_path(post) %> <% end %> </td>
            <td><% if current_user && post.user == current_user %><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    -->
    <div style="width: 50%;margin-left: 25%;margin-right: 25%;background-color: white;">
    <p style="background-color: lightblue;"><b><%= link_to 'Yeni gönderi', new_post_path %></b></p>
    <% @posts.reverse.each do |post| %>
        <table border="2">
          <tr>
            <% if current_user.departmant == post.user.departmant %>
              <td>
                <p><%= post.title %> posted by <b><%= post.user %></b> </p>
                <p><%= time_ago_in_words post.created_at %> ago </p>
                <!--<p><%= post.content %></p> -->
                <p><%= link_to 'Göster', post %> ( <%= post.likes.count %> beğeni , <%= post.comments.count %>   yorum )</p>
                <p><% if current_user && post.user == current_user %><%= link_to 'Düzenle', edit_post_path(post) %> <% end %> </p>
                <p><% if current_user && post.user == current_user %><%= link_to 'Sil', post, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %> </p>
              </td>
            <% end %>
          </tr>
        </table>      
    <% end %>


    </div>
  </body>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<p class="new"><%= link_to 'Back', posts_path %></p>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WallApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'myMain' %>

</head>

  <% @ifLiked = 0  %>
   <% @post.likes.each do |like| %>
      <% if like.userNameLiked == current_user.nick
        @ifLiked = 1 %>
    <% end %> 
  <% end %>



  <body style="background-color: lightblue;">
    <p>
    <div style="width: 50%;margin-left: 25%;margin-right: 25%;background-color: white;">
        <table border="2">
          <tr>
            <td>
              <p><b>User : <%= @post.user %></b> </p>
              <p> <b>Title : </b>   <%= @post.title %> (<%= time_ago_in_words @post.created_at %> ago) </p>
              <p><b>Post : </b></p>
              <p><%= @post.content %></p>
              <p><%= @post.likes.count %> Beğeni</p>
              <p>
                  <% if @ifLiked == 0 %>
                    <%= form_for [@post,@post.likes.build] do |l| %>
                      <div class="actions">
                        <%=  l.submit "Beğen" %>
                      </div>
                    <% end %>
                  <% else %>
                    <% @post.likes.each do |like| %>
                      <% if current_user.nick == like.userNameLiked %> 
                        <%= button_to "Vazgeç", {:controller => :likes,
                      :action => 'destroy', :id => like.id , :post_id => @post.id}, :method => :delete %>
                      <% end %>
                    <% end %>
                    <% end %>
               </p>
              <h2 >Yorumlar</h2>
              <% @post.comments.each do |comment| %>
                  <p > <%= comment.comm %> </p>
                  <p > <%= time_ago_in_words comment.created_at %> ago by <%= comment.userName %> </p>
                  <p > <% if current_user.nick == comment.userName %> <%= button_to "Yorumu sil", {:controller => :comments,
                      :action => 'destroy', :id => comment.id , :post_id => @post.id}, :method => :delete %>
                      <% end %>
                  </p>
                  <hr>
              <% end %>

              <%= form_for [@post,@post.comments.build] do |f| %>

                <div class="field">
                  <%= f.label :yorum %><br>
                  <%= f.text_area :comm %>
                </div>
                <div class="actions">
                  <%= f.submit "Yorum yap"%>
                </div>
              <% end %>
              <p>
              <% if current_user && @post.user == current_user %>
              <%= link_to 'Düzenle', edit_post_path(@post) %> |
              <% end %>
              <%= link_to 'Geri dön', posts_path %>
              </p>


            </td>
          </tr>
        </table>
    </div>



  </body>

</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nick %><br>
    <%= f.text_field :nick %>
  </div>
  <div class="field">
    <%= f.label :bölüm %><br>
    <%= f.select :departmant, [ 'Bilgisayar','Elektronik','Malzeme','Matematik' , 'Mimar', 'İsletme' , 'Fizik' , 'Genetik'], :prompt => 'Select One' %>  </div>
  <div class="field">
    <%= f.label :sifre %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :sifreTekrar %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WallApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'myMain' %>

</head>
<body>
    
  <h1>Listing Users</h1>

  <table>
    <thead>
      <tr>
        <th>Nick</th>
        <th>Departmant</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.nick %></td>
          <td><%= user.departmant %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <p class="new">
  <%= link_to 'New User', new_user_path %>
  </p>
</body>
</html>

app/views/users/new.html.erb
<h1>Yeni Üye</h1>

<%= render 'form' %>

<p class="new">
<%= link_to 'Back', users_path %>
</p>

app/views/users/show.html.erb
<p class="new">
  <strong>Nick:</strong>
  <%= @user.nick %>
</p>

<p class="new">
  <strong>Departmant:</strong>
  <%= @user.departmant %>
</p>

<p class="new">
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</p>